# -*- coding: utf-8 -*-
"""ATV_PraticaC2-Processamento Digital

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mpg56roy4QNPGVSiwHPJbBQXbS-mgDHV
"""

import rasterio
import numpy as np

pixels_soja = 0
pixels_pastagem = 0
pixels_sem_dados = 0
total_pixels = 0

with rasterio.open("imagem.tif") as src:
    block_shape = src.block_shapes[0]  # Tamanho dos blocos nativos
    for ji, window in src.block_windows(1):
        bloco = src.read(1, window=window)
        total_pixels += bloco.size
        pixels_soja += np.sum(bloco == 39)
        pixels_pastagem += np.sum(bloco == 15)
        pixels_sem_dados += np.sum(bloco == 0)

pixels_validos = total_pixels - pixels_sem_dados
percentual_soja = pixels_soja / pixels_validos
percentual_pastagem = pixels_pastagem / pixels_validos
area_brasil_ha = 851_576_000
area_soja_ha = percentual_soja * area_brasil_ha
area_pastagem_ha = percentual_pastagem * area_brasil_ha

print(f"Total de pixels: {total_pixels:,}")
print(f"Pixels sem dados: {pixels_sem_dados:,}")
print(f"Pixels soja: {pixels_soja:,}")
print(f"Pixels pastagem: {pixels_pastagem:,}")
print(f"\nÁrea soja: {area_soja_ha:,.0f} ha")
print(f"Área pastagem: {area_pastagem_ha:,.0f} ha")